name: Checkmarx One Auto Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  security-events: write

jobs:
  checkmarx-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Checkmarx One Scan
        uses: Checkmarx/ast-github-action@e3f1356c077fcb2ad2062ccc8c9f1631bae59128
        with:
          project_name: CHECK-MARX/Project_Shop_Site
          cx_tenant: sng_partners
          base_uri: https://sng.ast.checkmarx.net
          cx_client_id: ${{ secrets.CX_CLIENT_ID || secrets.CHECKMARX_CLIENT_ID || secrets.CXONE_CLIENT_ID }}
          cx_client_secret: ${{ secrets.CX_CLIENT_SECRET || secrets.CHECKMARX_CLIENT_SECRET || secrets.CXONE_CLIENT_SECRET }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          scan_params: >-
            --use-gitignore --file-filter '!**/venv/**,!**/node_modules/**,!**/scan_result/**,!**/backups/**,!**/uploads/**,!**/__pycache__/**'

